use crate::semantic::expr::{Expr, ExprKind, FoldOp, QueryKind, QueryNode, SetOp};
/// Exhaustive matches force new semantic variants to receive an inventory mapping.
pub fn operator_name(e: &Expr) -> &'static str {
    match e.kind() {
        ExprKind::Lit(_) => "Lit",
        ExprKind::Field { .. } => "Field",
        ExprKind::Param(_) => "Param",
        ExprKind::DerivedRef { .. } => "DerivedRef",
        ExprKind::Cmp(..) => "Cmp",
        ExprKind::Arith(..) => "Arith",
        ExprKind::And(_) => "And",
        ExprKind::Or(_) => "Or",
        ExprKind::Not(_) => "Not",
        ExprKind::In(..) => "In",
        ExprKind::IsNone(_) => "IsNone",
        ExprKind::IsSome(_) => "IsSome",
        ExprKind::ValueOr(..) => "ValueOr",
        ExprKind::Some(_) => "Some",
        ExprKind::ToDecimal(_) => "ToDecimal",
        ExprKind::Wrap(_) => "Wrap",
        ExprKind::Unwrap(_) => "Unwrap",
        ExprKind::Rescale { .. } => "Rescale",
        ExprKind::Exists(_) => "Exists",
        ExprKind::Referenced(_) => "Referenced",
        ExprKind::Count(_) => "Count",
        ExprKind::StrictUnwrap(_) => "StrictUnwrap",
        ExprKind::EnumMap { .. } => "EnumMap",
        ExprKind::Fold { op, .. } => match op {
            FoldOp::Any => "Any",
            FoldOp::All => "All",
            FoldOp::Sum => "Sum",
            FoldOp::Min => "Min",
            FoldOp::Max => "Max",
            FoldOp::Unique => "Unique",
        },
    }
}
pub fn query_name(q: &QueryNode) -> &'static str {
    match q.kind() {
        QueryKind::Select => "Select",
        QueryKind::Where { .. } => "Where",
        QueryKind::Set { op, .. } => match op {
            SetOp::Union => "Union",
            SetOp::Intersection => "Intersection",
            SetOp::Difference => "Difference",
        },
    }
}
pub const OPERATOR_NAMES: &[&str] = &[
    "Lit",
    "Field",
    "Param",
    "DerivedRef",
    "Cmp",
    "Arith",
    "And",
    "Or",
    "Not",
    "In",
    "IsNone",
    "IsSome",
    "ValueOr",
    "Some",
    "ToDecimal",
    "Wrap",
    "Unwrap",
    "Rescale",
    "Exists",
    "Referenced",
    "Count",
    "Any",
    "All",
    "Sum",
    "Min",
    "Max",
    "Unique",
    "StrictUnwrap",
    "EnumMap",
    "Select",
    "Where",
    "Union",
    "Intersection",
    "Difference",
];
